/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection */

#ifndef _Included_bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection
#define _Included_bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection
 * Method:    getDataUpForClient
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection_getDataUpForClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection
 * Method:    getDataDownForClient
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection_getDataDownForClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection
 * Method:    addClient
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection_addClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection
 * Method:    forgetClient
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection_forgetClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection
 * Method:    initPcap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection_initPcap
  (JNIEnv *, jobject);

/*
 * Class:     bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection
 * Method:    pcapLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection_pcapLoop
  (JNIEnv *, jobject);

/*
 * Class:     bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection
 * Method:    stopPcap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bitmesh_bitmeshmicropayments_jni_pcap_BitMeshDataCollection_stopPcap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
