/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BitMeshDataCollection */

#ifndef _Included_BitMeshDataCollection
#define _Included_BitMeshDataCollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BitMeshDataCollection
 * Method:    getDataUpForClient
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_BitMeshDataCollection_getDataUpForClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BitMeshDataCollection
 * Method:    getDataDownForClient
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_BitMeshDataCollection_getDataDownForClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BitMeshDataCollection
 * Method:    addClient
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BitMeshDataCollection_addClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BitMeshDataCollection
 * Method:    forgetClient
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BitMeshDataCollection_forgetClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BitMeshDataCollection
 * Method:    initPcap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BitMeshDataCollection_initPcap
  (JNIEnv *, jobject);

/*
 * Class:     BitMeshDataCollection
 * Method:    pcapLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BitMeshDataCollection_pcapLoop
  (JNIEnv *, jobject);

/*
 * Class:     BitMeshDataCollection
 * Method:    stopPcap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BitMeshDataCollection_stopPcap
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
